stages:
  - lint
  - test
  - publish

lint:
  image: golang:1.19
  stage: lint
  script:
    - go install golang.org/x/lint/golint@latest
    - go install github.com/kisielk/errcheck@latest
    - golint $(go list ./... | grep -v /vendor/)
    - errcheck $(go list ./... | grep -v /vendor/)

test:
  image: golang:1.19
  stage: test
  script:
    - go test ./...

publish:
  image: golang:1.19
  stage: publish
  services:
    - docker:18.09-dind
  script:
    - bash .release.sh
  only:
    - tags
